// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: lifecycle.sql

package store

import (
	"context"
)

const findRunCursor = `-- name: FindRunCursor :one
SELECT after_sequence FROM run_cursors WHERE cursor_id=? AND run_id=? AND principal_id=? AND environment=? AND project_id=?
`

type FindRunCursorParams struct {
	CursorID    string
	RunID       string
	PrincipalID string
	Environment string
	ProjectID   string
}

func (q *Queries) FindRunCursor(ctx context.Context, arg FindRunCursorParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, findRunCursor,
		arg.CursorID,
		arg.RunID,
		arg.PrincipalID,
		arg.Environment,
		arg.ProjectID,
	)
	var after_sequence int64
	err := row.Scan(&after_sequence)
	return after_sequence, err
}

const findStubDispatch = `-- name: FindStubDispatch :one
SELECT dispatch_token, envelope_digest, profile_revision, started_at, scenario, frozen_task FROM stub_dispatches WHERE dispatch_token=?
`

func (q *Queries) FindStubDispatch(ctx context.Context, dispatchToken string) (StubDispatch, error) {
	row := q.db.QueryRowContext(ctx, findStubDispatch, dispatchToken)
	var i StubDispatch
	err := row.Scan(
		&i.DispatchToken,
		&i.EnvelopeDigest,
		&i.ProfileRevision,
		&i.StartedAt,
		&i.Scenario,
		&i.FrozenTask,
	)
	return i, err
}

const getLifecycle = `-- name: GetLifecycle :one
SELECT run_id, principal_id, environment, project_id, phase, state, state_version, payload, adapter_sequence, event_sequence, lease_owner, lease_until FROM run_lifecycle WHERE run_id=?
`

func (q *Queries) GetLifecycle(ctx context.Context, runID string) (RunLifecycle, error) {
	row := q.db.QueryRowContext(ctx, getLifecycle, runID)
	var i RunLifecycle
	err := row.Scan(
		&i.RunID,
		&i.PrincipalID,
		&i.Environment,
		&i.ProjectID,
		&i.Phase,
		&i.State,
		&i.StateVersion,
		&i.Payload,
		&i.AdapterSequence,
		&i.EventSequence,
		&i.LeaseOwner,
		&i.LeaseUntil,
	)
	return i, err
}

const getPollWindow = `-- name: GetPollWindow :one
SELECT started_at,last_at,polls FROM run_poll_windows WHERE principal_id=? AND environment=? AND project_id=?
`

type GetPollWindowParams struct {
	PrincipalID string
	Environment string
	ProjectID   string
}

type GetPollWindowRow struct {
	StartedAt string
	LastAt    string
	Polls     int64
}

func (q *Queries) GetPollWindow(ctx context.Context, arg GetPollWindowParams) (GetPollWindowRow, error) {
	row := q.db.QueryRowContext(ctx, getPollWindow, arg.PrincipalID, arg.Environment, arg.ProjectID)
	var i GetPollWindowRow
	err := row.Scan(&i.StartedAt, &i.LastAt, &i.Polls)
	return i, err
}

const getRunCursor = `-- name: GetRunCursor :one
SELECT cursor_id FROM run_cursors WHERE run_id=? AND principal_id=? AND environment=? AND project_id=? AND after_sequence=?
`

type GetRunCursorParams struct {
	RunID         string
	PrincipalID   string
	Environment   string
	ProjectID     string
	AfterSequence int64
}

func (q *Queries) GetRunCursor(ctx context.Context, arg GetRunCursorParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getRunCursor,
		arg.RunID,
		arg.PrincipalID,
		arg.Environment,
		arg.ProjectID,
		arg.AfterSequence,
	)
	var cursor_id string
	err := row.Scan(&cursor_id)
	return cursor_id, err
}

const getRunResult = `-- name: GetRunResult :one
SELECT payload FROM run_results WHERE run_id=?
`

func (q *Queries) GetRunResult(ctx context.Context, runID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getRunResult, runID)
	var payload string
	err := row.Scan(&payload)
	return payload, err
}

const insertLifecycle = `-- name: InsertLifecycle :exec
INSERT INTO run_lifecycle(run_id,principal_id,environment,project_id,phase,state,state_version,payload)
VALUES (?, ?, ?, ?, 'queued','accepted',1,?)
`

type InsertLifecycleParams struct {
	RunID       string
	PrincipalID string
	Environment string
	ProjectID   string
	Payload     string
}

func (q *Queries) InsertLifecycle(ctx context.Context, arg InsertLifecycleParams) error {
	_, err := q.db.ExecContext(ctx, insertLifecycle,
		arg.RunID,
		arg.PrincipalID,
		arg.Environment,
		arg.ProjectID,
		arg.Payload,
	)
	return err
}

const insertRunCursor = `-- name: InsertRunCursor :exec
INSERT INTO run_cursors(cursor_id,run_id,principal_id,environment,project_id,after_sequence) VALUES(?,?,?,?,?,?)
`

type InsertRunCursorParams struct {
	CursorID      string
	RunID         string
	PrincipalID   string
	Environment   string
	ProjectID     string
	AfterSequence int64
}

func (q *Queries) InsertRunCursor(ctx context.Context, arg InsertRunCursorParams) error {
	_, err := q.db.ExecContext(ctx, insertRunCursor,
		arg.CursorID,
		arg.RunID,
		arg.PrincipalID,
		arg.Environment,
		arg.ProjectID,
		arg.AfterSequence,
	)
	return err
}

const insertRunEvent = `-- name: InsertRunEvent :exec
INSERT INTO run_events(run_id,sequence,payload) VALUES(?,?,?)
`

type InsertRunEventParams struct {
	RunID    string
	Sequence int64
	Payload  string
}

func (q *Queries) InsertRunEvent(ctx context.Context, arg InsertRunEventParams) error {
	_, err := q.db.ExecContext(ctx, insertRunEvent, arg.RunID, arg.Sequence, arg.Payload)
	return err
}

const insertRunResult = `-- name: InsertRunResult :exec
INSERT INTO run_results(run_id,payload) VALUES(?,?)
`

type InsertRunResultParams struct {
	RunID   string
	Payload string
}

func (q *Queries) InsertRunResult(ctx context.Context, arg InsertRunResultParams) error {
	_, err := q.db.ExecContext(ctx, insertRunResult, arg.RunID, arg.Payload)
	return err
}

const insertStubDispatch = `-- name: InsertStubDispatch :exec
INSERT INTO stub_dispatches(dispatch_token,envelope_digest,profile_revision,started_at,scenario,frozen_task)
VALUES(?,?,?,?,?,?) ON CONFLICT(dispatch_token) DO NOTHING
`

type InsertStubDispatchParams struct {
	DispatchToken   string
	EnvelopeDigest  string
	ProfileRevision string
	StartedAt       string
	Scenario        string
	FrozenTask      string
}

func (q *Queries) InsertStubDispatch(ctx context.Context, arg InsertStubDispatchParams) error {
	_, err := q.db.ExecContext(ctx, insertStubDispatch,
		arg.DispatchToken,
		arg.EnvelopeDigest,
		arg.ProfileRevision,
		arg.StartedAt,
		arg.Scenario,
		arg.FrozenTask,
	)
	return err
}

const listRunEvents = `-- name: ListRunEvents :many
SELECT payload FROM run_events WHERE run_id=? AND sequence>? ORDER BY sequence LIMIT 101
`

type ListRunEventsParams struct {
	RunID    string
	Sequence int64
}

func (q *Queries) ListRunEvents(ctx context.Context, arg ListRunEventsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRunEvents, arg.RunID, arg.Sequence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var payload string
		if err := rows.Scan(&payload); err != nil {
			return nil, err
		}
		items = append(items, payload)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPollWindow = `-- name: SetPollWindow :exec
INSERT INTO run_poll_windows(principal_id,environment,project_id,started_at,last_at,polls) VALUES(?,?,?,?,?,?)
ON CONFLICT(principal_id,environment,project_id) DO UPDATE SET started_at=excluded.started_at,last_at=excluded.last_at,polls=excluded.polls
`

type SetPollWindowParams struct {
	PrincipalID string
	Environment string
	ProjectID   string
	StartedAt   string
	LastAt      string
	Polls       int64
}

func (q *Queries) SetPollWindow(ctx context.Context, arg SetPollWindowParams) error {
	_, err := q.db.ExecContext(ctx, setPollWindow,
		arg.PrincipalID,
		arg.Environment,
		arg.ProjectID,
		arg.StartedAt,
		arg.LastAt,
		arg.Polls,
	)
	return err
}

const updateLifecycle = `-- name: UpdateLifecycle :execrows
UPDATE run_lifecycle SET phase=?,state=?,state_version=?,payload=?,adapter_sequence=?,event_sequence=?,lease_owner=?,lease_until=?
WHERE run_id=? AND state_version=? AND lease_owner=?
`

type UpdateLifecycleParams struct {
	Phase           string
	State           string
	StateVersion    int64
	Payload         string
	AdapterSequence int64
	EventSequence   int64
	LeaseOwner      string
	LeaseUntil      string
	RunID           string
	StateVersion_2  int64
	LeaseOwner_2    string
}

func (q *Queries) UpdateLifecycle(ctx context.Context, arg UpdateLifecycleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateLifecycle,
		arg.Phase,
		arg.State,
		arg.StateVersion,
		arg.Payload,
		arg.AdapterSequence,
		arg.EventSequence,
		arg.LeaseOwner,
		arg.LeaseUntil,
		arg.RunID,
		arg.StateVersion_2,
		arg.LeaseOwner_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const workerCandidate = `-- name: WorkerCandidate :one
SELECT l.run_id, l.principal_id, l.environment, l.project_id, l.phase, l.state, l.state_version, l.payload, l.adapter_sequence, l.event_sequence, l.lease_owner, l.lease_until, t.dispatch_token, a.frozen_review FROM run_lifecycle l
JOIN task_runs t USING(run_id) JOIN approvals a USING(approval_id)
WHERE l.principal_id=? AND l.environment=? AND l.project_id=? AND l.phase!='terminal'
ORDER BY CASE l.phase WHEN 'active' THEN 0 ELSE 1 END, t.rowid LIMIT 1
`

type WorkerCandidateParams struct {
	PrincipalID string
	Environment string
	ProjectID   string
}

type WorkerCandidateRow struct {
	RunID           string
	PrincipalID     string
	Environment     string
	ProjectID       string
	Phase           string
	State           string
	StateVersion    int64
	Payload         string
	AdapterSequence int64
	EventSequence   int64
	LeaseOwner      string
	LeaseUntil      string
	DispatchToken   string
	FrozenReview    string
}

func (q *Queries) WorkerCandidate(ctx context.Context, arg WorkerCandidateParams) (WorkerCandidateRow, error) {
	row := q.db.QueryRowContext(ctx, workerCandidate, arg.PrincipalID, arg.Environment, arg.ProjectID)
	var i WorkerCandidateRow
	err := row.Scan(
		&i.RunID,
		&i.PrincipalID,
		&i.Environment,
		&i.ProjectID,
		&i.Phase,
		&i.State,
		&i.StateVersion,
		&i.Payload,
		&i.AdapterSequence,
		&i.EventSequence,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.DispatchToken,
		&i.FrozenReview,
	)
	return i, err
}
