// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"database/sql"
)

type Approval struct {
	ApprovalID     string
	PrincipalID    string
	Environment    string
	ProjectID      string
	EnvelopeDigest string
	FrozenReview   string
	ExpiresAt      string
	ConsumedRunID  sql.NullString
}

type Receipt struct {
	Sequence  int64
	ReceiptID string
	Payload   string
}

type RunCursor struct {
	CursorID      string
	RunID         string
	PrincipalID   string
	Environment   string
	ProjectID     string
	AfterSequence int64
}

type RunEvent struct {
	RunID    string
	Sequence int64
	Payload  string
}

type RunLifecycle struct {
	RunID           string
	PrincipalID     string
	Environment     string
	ProjectID       string
	Phase           string
	State           string
	StateVersion    int64
	Payload         string
	AdapterSequence int64
	EventSequence   int64
	LeaseOwner      string
	LeaseUntil      string
}

type RunPollWindow struct {
	PrincipalID string
	Environment string
	ProjectID   string
	StartedAt   string
	LastAt      string
	Polls       int64
}

type RunResult struct {
	RunID   string
	Payload string
}

type StubDispatch struct {
	DispatchToken   string
	EnvelopeDigest  string
	ProfileRevision string
	StartedAt       string
	Scenario        string
	FrozenTask      string
}

type TaskRun struct {
	RunID          string
	PrincipalID    string
	Environment    string
	ProjectID      string
	Operation      string
	IdempotencyKey string
	InputDigest    string
	ApprovalID     string
	DispatchToken  string
	Payload        string
}
