// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: receipts.sql

package store

import (
	"context"
)

const finalizeReceipt = `-- name: FinalizeReceipt :execrows
UPDATE receipts SET payload = ? WHERE sequence = ?
`

type FinalizeReceiptParams struct {
	Payload  string
	Sequence int64
}

func (q *Queries) FinalizeReceipt(ctx context.Context, arg FinalizeReceiptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finalizeReceipt, arg.Payload, arg.Sequence)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getReceipt = `-- name: GetReceipt :one
SELECT payload FROM receipts WHERE receipt_id = ?
`

func (q *Queries) GetReceipt(ctx context.Context, receiptID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getReceipt, receiptID)
	var payload string
	err := row.Scan(&payload)
	return payload, err
}

const insertReceipt = `-- name: InsertReceipt :one
INSERT INTO receipts (receipt_id, payload)
VALUES (?, ?)
RETURNING sequence
`

type InsertReceiptParams struct {
	ReceiptID string
	Payload   string
}

func (q *Queries) InsertReceipt(ctx context.Context, arg InsertReceiptParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertReceipt, arg.ReceiptID, arg.Payload)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}
