// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tasks.sql

package store

import (
	"context"
	"database/sql"
)

const consumeApproval = `-- name: ConsumeApproval :execrows
UPDATE approvals SET consumed_run_id = ?
WHERE approval_id = ? AND consumed_run_id IS NULL
`

type ConsumeApprovalParams struct {
	ConsumedRunID sql.NullString
	ApprovalID    string
}

func (q *Queries) ConsumeApproval(ctx context.Context, arg ConsumeApprovalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeApproval, arg.ConsumedRunID, arg.ApprovalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countPendingRuns = `-- name: CountPendingRuns :one
SELECT COUNT(*) FROM task_runs WHERE project_id = ? AND environment = ?
`

type CountPendingRunsParams struct {
	ProjectID   string
	Environment string
}

func (q *Queries) CountPendingRuns(ctx context.Context, arg CountPendingRunsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingRuns, arg.ProjectID, arg.Environment)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findApproval = `-- name: FindApproval :one
SELECT envelope_digest, expires_at, consumed_run_id FROM approvals
WHERE approval_id = ? AND principal_id = ? AND environment = ? AND project_id = ?
`

type FindApprovalParams struct {
	ApprovalID  string
	PrincipalID string
	Environment string
	ProjectID   string
}

type FindApprovalRow struct {
	EnvelopeDigest string
	ExpiresAt      string
	ConsumedRunID  sql.NullString
}

func (q *Queries) FindApproval(ctx context.Context, arg FindApprovalParams) (FindApprovalRow, error) {
	row := q.db.QueryRowContext(ctx, findApproval,
		arg.ApprovalID,
		arg.PrincipalID,
		arg.Environment,
		arg.ProjectID,
	)
	var i FindApprovalRow
	err := row.Scan(&i.EnvelopeDigest, &i.ExpiresAt, &i.ConsumedRunID)
	return i, err
}

const findRun = `-- name: FindRun :one
SELECT payload, approval_id FROM task_runs
WHERE principal_id = ? AND environment = ? AND project_id = ? AND run_id = ?
`

type FindRunParams struct {
	PrincipalID string
	Environment string
	ProjectID   string
	RunID       string
}

type FindRunRow struct {
	Payload    string
	ApprovalID string
}

func (q *Queries) FindRun(ctx context.Context, arg FindRunParams) (FindRunRow, error) {
	row := q.db.QueryRowContext(ctx, findRun,
		arg.PrincipalID,
		arg.Environment,
		arg.ProjectID,
		arg.RunID,
	)
	var i FindRunRow
	err := row.Scan(&i.Payload, &i.ApprovalID)
	return i, err
}

const findSubmission = `-- name: FindSubmission :one
SELECT payload, input_digest, approval_id FROM task_runs
WHERE principal_id = ? AND environment = ? AND project_id = ? AND operation = 'submit_task' AND idempotency_key = ?
`

type FindSubmissionParams struct {
	PrincipalID    string
	Environment    string
	ProjectID      string
	IdempotencyKey string
}

type FindSubmissionRow struct {
	Payload     string
	InputDigest string
	ApprovalID  string
}

func (q *Queries) FindSubmission(ctx context.Context, arg FindSubmissionParams) (FindSubmissionRow, error) {
	row := q.db.QueryRowContext(ctx, findSubmission,
		arg.PrincipalID,
		arg.Environment,
		arg.ProjectID,
		arg.IdempotencyKey,
	)
	var i FindSubmissionRow
	err := row.Scan(&i.Payload, &i.InputDigest, &i.ApprovalID)
	return i, err
}

const insertApproval = `-- name: InsertApproval :exec
INSERT INTO approvals (approval_id, principal_id, environment, project_id, envelope_digest, frozen_review, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertApprovalParams struct {
	ApprovalID     string
	PrincipalID    string
	Environment    string
	ProjectID      string
	EnvelopeDigest string
	FrozenReview   string
	ExpiresAt      string
}

func (q *Queries) InsertApproval(ctx context.Context, arg InsertApprovalParams) error {
	_, err := q.db.ExecContext(ctx, insertApproval,
		arg.ApprovalID,
		arg.PrincipalID,
		arg.Environment,
		arg.ProjectID,
		arg.EnvelopeDigest,
		arg.FrozenReview,
		arg.ExpiresAt,
	)
	return err
}

const insertTaskRun = `-- name: InsertTaskRun :exec
INSERT INTO task_runs (run_id, principal_id, environment, project_id, operation, idempotency_key, input_digest, approval_id, dispatch_token, payload)
VALUES (?, ?, ?, ?, 'submit_task', ?, ?, ?, ?, ?)
`

type InsertTaskRunParams struct {
	RunID          string
	PrincipalID    string
	Environment    string
	ProjectID      string
	IdempotencyKey string
	InputDigest    string
	ApprovalID     string
	DispatchToken  string
	Payload        string
}

func (q *Queries) InsertTaskRun(ctx context.Context, arg InsertTaskRunParams) error {
	_, err := q.db.ExecContext(ctx, insertTaskRun,
		arg.RunID,
		arg.PrincipalID,
		arg.Environment,
		arg.ProjectID,
		arg.IdempotencyKey,
		arg.InputDigest,
		arg.ApprovalID,
		arg.DispatchToken,
		arg.Payload,
	)
	return err
}
